image: node:12-buster

publish_vsce:
  stage: deploy
  script:
    - npx vsce publish -p "$VSCE_TOKEN" --baseImagesUrl https://gitlab.com/zerodind/familiar-java-themes/-/raw/master/
  only:
    - master
  when: manual
  allow_failure: false

publish_ovsx:
  stage: deploy
  script:
    - npx ovsx publish -p "$OVSX_TOKEN" --baseImagesUrl https://gitlab.com/zerodind/familiar-java-themes/-/raw/master/
  only:
    - master
  when: manual
  allow_failure: false
